name: Pulp-Papier
favicon: null
layout_spectrum: 0.5833118669688702
typography_spectrum: 0.8312598143238574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.649656223366037
  lightness: 0.1572981143835932
  saturation: 0.29741549608297646
  rhythmicContrast: 0.5995713223237544
purpose: []
